#SQL
spring.datasource.url=${POSTGRES_URL:jdbc:postgresql://localhost:5434/notification_db}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${POSTGRES_USERNAME:dev}
spring.datasource.password=${POSTGRES_PASSWORD:dev123}
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#Email
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:bankchuhmanov@gmail.com}
spring.mail.password=${MAIL_PASSWORD:tslkelmtkvlmjnat}
notification.email.from=${EMAIL_FROM:bankchuhmanov@gmail.com}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.transport.protocol=smtp
#Actuator
management.endpoints.web.exposure.include=*
management.endpoint.env.show-values=always
management.endpoint.configprops.show-values=always
#Logging
logging.level.ru.bank.notification_service=DEBUG
logging.level.org.springframework.cloud.config=DEBUG
logging.level.org.springframework.kafka=DEBUG
logging.level.org.springframework.mail=DEBUG
spring.mail.debug=true