#Timeouts ms
spring.cloud.gateway.server.webflux.httpclient.connect-timeout=10000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=30000
spring.cloud.gateway.server.webflux.httpclient.pool.max-connections=1000
spring.cloud.gateway.server.webflux.httpclient.pool.acquire-timeout=60000
#Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=never
management.endpoint.env.show-values=never
management.endpoint.configprops.show-values=never
#Logs
logging.level.root=WARN
logging.level.ru.bank.gateway=WARN
logging.level.org.springframework.cloud.gateway=WARN