# Routes
# Route 1: Auth Service Public-Endpoints
spring.cloud.gateway.routes[0].id=auth-service-public
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/login,/auth/refresh/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[0].filters[1].name=AddResponseHeader
spring.cloud.gateway.routes[0].filters[1].args.name=X-Service
spring.cloud.gateway.routes[0].filters[1].args.value=auth-public

#Logs
logging.level.root=INFO
logging.level.ru.bank.gateway=INFO