#Application
spring.application.name=api-gateway
server.port=8092
# Auto - Routs - Eureka
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
# Timeouts ms
spring.cloud.gateway.server.webflux.httpclient.connect-timeout=5000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=10000
spring.cloud.gateway.server.webflux.httpclient.pool.max-connections=500
spring.cloud.gateway.server.webflux.httpclient.pool.acquire-timeout=45000
# Actuator
management.endpoints.web.exposure.include=health,info,refresh,env,configprops
management.endpoint.health.show-details=always