# Timeout ms
spring.cloud.gateway.server.webflux.httpclient.connect-timeout=3000
spring.cloud.gateway.server.webflux.httpclient.response-timeout=5000
# Actuator all
management.endpoints.web.exposure.include=*
management.endpoint.env.show-values=always
management.endpoint.configprops.show-values=always
#Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6380}6380
spring.data.redis.password=${REDIS_PASSWORD:redis123}
# Logs
logging.level.ru.bank.gateway=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator=DEBUG