#Application
spring.application.name=api-gateway
server.port=8092
test.message = "Hello Config Service"
test.environment=dev
test.timestamp=2026-08-04
spring.cloud.gateway.enabled=true
info.app.name=api-gateway
info.app.version=1.0.0
info.app.description=API Gateway for Bank Microservices
management.endpoints.web.exposure.include=health,info,refresh,env,configprops
management.endpoint.health.show-details=always