#Application
spring.application.name=auth-service
server.port=8090
#Jwt
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh-expiration=${JWT_REFRESH_EXPIRATION:604800000}
jwt.private-key-path=${JWT_PRIVATE_KEY_PATH:keys/demo-private-key.pem}
jwt.public-key-path=${JWT_PUBLIC_KEY_PATH:keys/demo-public-key.pem}
#Redis
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0