#SQL
spring.datasource.url=jdbc:postgresql://localhost:5433/auth_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=dev
spring.datasource.password=dev123
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#JWT
jwt.secret=dev-secret-key-for-testing-only
#Logging
logging.level.com.bank.auth=DEBUG
logging.level.org.springframework.cloud.config=DEBUG
test.property=last-test-bus-test
