#SQL
spring.datasource.url=jdbc:postgresql://prod-db:5433/auth_prod
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
#JWT
jwt.secret=${JWT_SECRET}
#Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
#Logging
logging.level.com.bank.auth=WARN
